<?php

namespace smart\apidoc\controllers;

use smart\apidoc\models\ApiDoc;
use yii\web\Controller;

/**
 * Default controller for the `v1` module
 */
class DefaultController extends Controller
{
    public $modelClass = '';

    public $layout = 'main';


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }



    public function actionIndex()
    {
        /** @var $module \smart\apidoc\Module */
        $module = $this->module;

        //$this->module->id
        $ApiDoc = new ApiDoc();
        $ApiDoc->skipModulesId = $module->skipModulesId;

        $detail =  $ApiDoc->getAllApiDoc();

        $modelsDoc = [];
        if(!empty($module->entitiesNamespace)){
            $modelsDoc = $ApiDoc->getAllModelsDoc($module->entitiesNamespace);
        }

        return $this->render('index.php',[
            'apiDetail' => $detail,
            'modelsDoc' => $modelsDoc,
        ]);
    }




}
