<?php

namespace smart\apidoc\controllers;

use smart\apidoc\models\ApiDoc;
use yii\web\Controller;

/**
 * Default controller for the `v1` module
 */
class DefaultController extends Controller
{
    public $modelClass = '';

    public $layout = 'main';


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }


    public function actionIndex()
    {
        /** @var $module \smart\apidoc\Module */
        $module = $this->module;

        //$this->module->id
        $ApiDoc = new ApiDoc();
        $ApiDoc->skipModulesId = $module->skipModulesId;


        //获取接口列表
        $apiList = $ApiDoc->getAllApiDoc();


        //获取README.md
        $readmeFileContent = '';
        $readmeFile = \Yii::getAlias($module->readMeFile);
        if ($readmeFile and file_exists($readmeFile)) {
            $readmeFileContent = file_get_contents($readmeFile);
        }

        //获取实体对象列表
        $modelsDoc = [];
        if (!empty($module->entitiesNamespace)) {
            $params = explode('\\', $module->entitiesNamespace);
            array_shift($params);
            $entitiesPath = \Yii::getAlias('@app') . '/' . implode('/', $params);
            $modelsDoc = $ApiDoc->getAllModelsDoc($module->entitiesNamespace, $entitiesPath);
        }

        return $this->render('index.php', [
            'readmeFileContent' => $readmeFileContent,
            'apiList' => $apiList,
            'modelsDoc' => $modelsDoc,
        ]);
    }


}
